- hosts: all
  handlers:
    - name: Test
      listen: my_handler
      command: echo "hello"
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      configs_packs:
        - sources:
            - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/default/assets/configs/test1"
          destination: /configs/test1
          variables:
            a: 10
            b: 20
        - sources:
            - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/default/assets/configs/test2"
          destination: /configs/test2
          variables:
            x: 100
            y: 200
          notify:
            - my_handler
